# Find include file:
FIND_PATH(SFMLwindow_INCLUDE_DIR SFML/Window.hpp)
# Find library:
FIND_LIBRARY(SFMLwindow_LIBRARIES NAMES sfml-window)
# Set success status:
IF (SFMLwindow_LIBRARIES AND SFMLwindow_INCLUDE_DIR)
	SET(SFMLwindow_FOUND "YES")
ELSE (SFMLwindow_LIBRARIES AND SFMLwindow_INCLUDE_DIR)
	SET(SFMLwindow_FOUND "NO")
ENDIF (SFMLwindow_LIBRARIES AND SFMLwindow_INCLUDE_DIR)

IF (SFMLwindow_FOUND)
	IF (NOT SFMLwindow_FIND_QUIETLY)
		MESSAGE(STATUS "Found SFMLwindow: ${SFMLwindow_LIBRARIES}")
	ENDIF (NOT SFMLwindow_FIND_QUIETLY)
ELSE (SFMLwindow_FOUND)
	IF (SFMLwindow_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find SFMLwindow library")
	ENDIF (SFMLwindow_FIND_REQUIRED)
ENDIF (SFMLwindow_FOUND)

MARK_AS_ADVANCED(SFMLwindow_LIBRARIES SFMLwindow_INCLUDE_DIR)
