# Find include file & library:
IF (UNIX)
	find_path(SFMLgraphics_INCLUDE_DIR SFML/Graphics.hpp)
	find_library(SFMLgraphics_LIBRARIES NAMES sfml-graphics)
ELSEIF (WIN32)
	set(SFMLgraphics_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/include/)
	set(SFMLgraphics_LIBRARIES ${CMAKE_SOURCE_DIR}/sfml-graphics-2.dll)
ENDIF (UNIX)
# Set success status:
IF (SFMLgraphics_LIBRARIES AND SFMLgraphics_INCLUDE_DIR)
	set(SFMLgraphics_FOUND "YES")
ELSE (SFMLgraphics_LIBRARIES AND SFMLgraphics_INCLUDE_DIR)
	set(SFMLgraphics_FOUND "NO")
ENDIF (SFMLgraphics_LIBRARIES AND SFMLgraphics_INCLUDE_DIR)

IF (SFMLgraphics_FOUND)
	IF (NOT SFMLgraphics_FIND_QUIETLY)
		message(STATUS "Found SFML-graphics: ${SFMLgraphics_LIBRARIES}")
	ENDIF (NOT SFMLgraphics_FIND_QUIETLY)
ELSE (SFMLgraphics_FOUND)
	IF (SFMLgraphics_FIND_REQUIRED)
		message(FATAL_ERROR "Could not find SFML-graphics library")
	ENDIF (SFMLgraphics_FIND_REQUIRED)
ENDIF (SFMLgraphics_FOUND)

mark_as_advanced(SFMLgraphics_LIBRARIES SFMLgraphics_INCLUDE_DIR)
