# Find include file:
FIND_PATH(LIBAVCODEC_INCLUDE_DIR libavcodec/avcodec.h)
# Find library:
FIND_LIBRARY(LIBAVCODEC_LIBRARIES NAMES avcodec)
# Set success status:
IF (LIBAVCODEC_LIBRARIES AND LIBAVCODEC_INCLUDE_DIR)
	SET(LIBAVCODEC_FOUND "YES")
ELSE (LIBAVCODEC_LIBRARIES AND LIBAVCODEC_INCLUDE_DIR)
	SET(LIBAVCODEC_FOUND "NO")
ENDIF (LIBAVCODEC_LIBRARIES AND LIBAVCODEC_INCLUDE_DIR)

IF (LIBAVCODEC_FOUND)
	IF (NOT LIBAVCODEC_FIND_QUIETLY)
		MESSAGE(STATUS "Found LIBAVCODEC: ${LIBAVCODEC_LIBRARIES}")
	ENDIF (NOT LIBAVCODEC_FIND_QUIETLY)
ELSE (LIBAVCODEC_FOUND)
	IF (LIBAVCODEC_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find LIBAVCODEC library")
	ENDIF (LIBAVCODEC_FIND_REQUIRED)
ENDIF (LIBAVCODEC_FOUND)

MARK_AS_ADVANCED(LIBAVCODEC_LIBRARIES LIBAVCODEC_INCLUDE_DIR)
