# Find include file:
find_path(LIBAVFORMAT_INCLUDE_DIR libavformat/avformat.h)
# Find library:
find_library(LIBAVFORMAT_LIBRARIES NAMES avformat)
# Set success status:
IF (LIBAVFORMAT_LIBRARIES AND LIBAVFORMAT_INCLUDE_DIR)
	set(LIBAVFORMAT_FOUND "YES")
ELSE (LIBAVFORMAT_LIBRARIES AND LIBAVFORMAT_INCLUDE_DIR)
	set(LIBAVFORMAT_FOUND "NO")
ENDIF (LIBAVFORMAT_LIBRARIES AND LIBAVFORMAT_INCLUDE_DIR)

IF (LIBAVFORMAT_FOUND)
	IF (NOT LIBAVFORMAT_FIND_QUIETLY)
		message(STATUS "Found LIBAVFORMAT: ${LIBAVFORMAT_LIBRARIES}")
	ENDIF (NOT LIBAVFORMAT_FIND_QUIETLY)
ELSE (LIBAVFORMAT_FOUND)
	IF (LIBAVFORMAT_FIND_REQUIRED)
		message(FATAL_ERROR "Could not find LIBAVFORMAT library")
	ENDIF (LIBAVFORMAT_FIND_REQUIRED)
ENDIF (LIBAVFORMAT_FOUND)

mark_as_advanced(LIBAVFORMAT_LIBRARIES LIBAVFORMAT_INCLUDE_DIR)
