# Find include file:
FIND_PATH(LIBAVFORMAT_INCLUDE_DIR libavformat/avformat.h)
# Find library:
FIND_LIBRARY(LIBAVFORMAT_LIBRARIES NAMES avformat)
# Set success status:
IF (LIBAVFORMAT_LIBRARIES AND LIBAVFORMAT_INCLUDE_DIR)
	SET(LIBAVFORMAT_FOUND "YES")
ELSE (LIBAVFORMAT_LIBRARIES AND LIBAVFORMAT_INCLUDE_DIR)
	SET(LIBAVFORMAT_FOUND "NO")
ENDIF (LIBAVFORMAT_LIBRARIES AND LIBAVFORMAT_INCLUDE_DIR)

IF (LIBAVFORMAT_FOUND)
	IF (NOT LIBAVFORMAT_FIND_QUIETLY)
		MESSAGE(STATUS "Found LIBAVFORMAT: ${LIBAVFORMAT_LIBRARIES}")
	ENDIF (NOT LIBAVFORMAT_FIND_QUIETLY)
ELSE (LIBAVFORMAT_FOUND)
	IF (LIBAVFORMAT_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find LIBAVFORMAT library")
	ENDIF (LIBAVFORMAT_FIND_REQUIRED)
ENDIF (LIBAVFORMAT_FOUND)

MARK_AS_ADVANCED(LIBAVFORMAT_LIBRARIES LIBAVFORMAT_INCLUDE_DIR)
