# Find include file:
find_path(LIBAVCODEC_INCLUDE_DIR libavcodec/avcodec.h)
# Find library:
find_library(LIBAVCODEC_LIBRARIES NAMES avcodec)
# Set success status:
IF (LIBAVCODEC_LIBRARIES AND LIBAVCODEC_INCLUDE_DIR)
	set(LIBAVCODEC_FOUND "YES")
ELSE (LIBAVCODEC_LIBRARIES AND LIBAVCODEC_INCLUDE_DIR)
	set(LIBAVCODEC_FOUND "NO")
ENDIF (LIBAVCODEC_LIBRARIES AND LIBAVCODEC_INCLUDE_DIR)

IF (LIBAVCODEC_FOUND)
	IF (NOT LIBAVCODEC_FIND_QUIETLY)
		message(STATUS "Found LIBAVCODEC: ${LIBAVCODEC_LIBRARIES}")
	ENDIF (NOT LIBAVCODEC_FIND_QUIETLY)
ELSE (LIBAVCODEC_FOUND)
	IF (LIBAVCODEC_FIND_REQUIRED)
		message(FATAL_ERROR "Could not find LIBAVCODEC library")
	ENDIF (LIBAVCODEC_FIND_REQUIRED)
ENDIF (LIBAVCODEC_FOUND)

mark_as_advanced(LIBAVCODEC_LIBRARIES LIBAVCODEC_INCLUDE_DIR)
